### model
model_name_or_path: /opt/share/chatglm/models/meta/Meta-Llama-3-8B-Instruct
adapter_name_or_path: /opt/share/chatglm/models/finetune/Meta-Llama-3-8B-Instruct-Comm100-Lora
template: llama3
finetuning_type: lora
# trust_remote_code: true

### export
export_dir: /opt/share/chatglm/models/finetune/Meta-Llama-3-8B-Instruct-Comm100
export_size: 2
export_device: cpu
export_legacy_format: false
