### NOTE: RLHF以及DPO对于文生文的任务会好一些(摘要生成和单轮对话)，如果你是分类任务，可能需要在SFT上面多下功夫，而不是DPO。DPO的训练损失跟推理不再是同一个任务，所以几乎没有指令遵循能力。

### model
model_name_or_path: /opt/share/chatglm/models/qwen/Qwen2.5-14B-Instruct

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: Comm100_LLM_dpo
template: qwen
cutoff_len: 4096 # 指定处理数据时的截断长度(Token数量)
max_samples: 1000 # 最大加载样本数
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /opt/share/chatglm/models/finetune/Qwen2.5-14B-Instruct-Comm100-Dpo-Lora
logging_steps: 1
save_steps: 10
save_total_limit: 5
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
flash_attn: fa2
bf16: true
# use_cache: False
