### model
model_name_or_path: /opt/share/chatglm/models/qwen/Qwen2.5-14B-Instruct
resume_from_checkpoint: /opt/share/chatglm/models/finetune/Qwen2.5-14B-Instruct-Comm100-Lora/checkpoint-600
# trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: Comm100_LLM
template: qwen
cutoff_len: 4096
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /opt/share/chatglm/models/finetune/Qwen2.5-14B-Instruct-Comm100-Lora
logging_steps: 10
save_steps: 100
save_total_limit: 5
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 15.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
flash_attn: fa2
bf16: true
